### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by oliverlinux** [edwin170/dualboot-ios-15-with-14-script#1]
For the version argument do you put your desired version or the version the device is currently on

**Comment by edwin170** [comment]
> For the version argument do you put your desired version or the version the device is currently on

You have to put the version that you want to dual boot for example my iPhone is on iOS 15 and I want dual boot with iOS 14.3 so you put on version iOS 14.3

**Comment by edwin170** [comment]
Or you can put the version of your ipsw
