### ISSUE TITLE
hdiutil: attach failed - Permission denied

### ISSUE THREAD

**Issue by eurosatofficial** [edwin170/dualboot-ios-15-with-14-script#112]
Got this error after the ramdisk downloading. any ideas?

``` 100% [===================================================================================================>]
download succeeded
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:06 ECID:000004B58B55FB48 IBFL:1C SRTG:[iBoot-2234.0.0.3.3] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:06 ECID:000004B58B55FB48 IBFL:1C SRTG:[iBoot-2234.0.0.3.3] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 15 iBoot detected!
getting get_sigcheck_patch() patch
applying patch=0x18038db94 : 000080d2
applying patch=0x18038db50 : 000080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 15 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1 ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x87000d474 : 000080d2
applying patch=0x87000d430 : 000080d2
applying patch=0x870001d28 : 000080d2c0035fd6
applying patch=0x870001d80 : 000080d2c0035fd6
applying patch=0x870031f74 : 000080d2c0035fd6
applying patch=0x87000f038 : 200080d2
applying patch=0x870010658 : 1ad30610
applying patch=0x87001e0b8 : 72643d6d64302064656275673d30783230313465202d76207764743d2d312000
applying patch=0x870014184 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8020 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x973ee1
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x1076c64
get_amfi_out_of_my_way_patch: Patching AMFI at 0x10722a8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
hdiutil: attach failed - Permission denied
[-] An error occurred ``` `````` `````` ```

[dualr1n hdiutil.txt](https://github.com/user-attachments/files/17669306/dualr1n.hdiutil.txt)

**Comment by dualra1n** [comment]
> Got this error after the ramdisk downloading. any ideas?
> 
> ```
> download succeeded
> usb_timeout: 5
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:06 ECID:000004B58B55FB48 IBFL:1C SRTG:[iBoot-2234.0.0.3.3] PWND:[gaster]
> Found the USB handle.
> Now you can boot untrusted images.
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> Found the USB handle.
> usb_timeout: 5
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:06 ECID:000004B58B55FB48 IBFL:1C SRTG:[iBoot-2234.0.0.3.3] PWND:[gaster]
> Found the USB handle.
> Now you can boot untrusted images.
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> Found the USB handle.
> main: Starting...
> iOS 15 iBoot detected!
> getting get_sigcheck_patch() patch
> applying patch=0x18038db94 : 000080d2
> applying patch=0x18038db50 : 000080d2
> main: Writing out patched file to work/iBSS.patched...
> main: Quitting...
> none
> main: Starting...
> iOS 15 iBoot detected!
> getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1 ) patch
> getting get_debug_enabled_patch() patch
> getting get_unlock_nvram_patch() patch
> getting get_sigcheck_patch() patch
> applying patch=0x87000d474 : 000080d2
> applying patch=0x87000d430 : 000080d2
> applying patch=0x870001d28 : 000080d2c0035fd6
> applying patch=0x870001d80 : 000080d2c0035fd6
> applying patch=0x870031f74 : 000080d2c0035fd6
> applying patch=0x87000f038 : 200080d2
> applying patch=0x870010658 : 1ad30610
> applying patch=0x87001e0b8 : 72643d6d64302064656275673d30783230313465202d76207764743d2d312000
> applying patch=0x870014184 : 1f2003d5
> main: Writing out patched file to work/iBEC.patched...
> main: Quitting...
> none
> krnl
> main: Starting...
> Kernel: Adding AMFI_get_out_of_my_way patch...
> get_amfi_out_of_my_way_patch: Entering ...
> get_amfi_out_of_my_way_patch: Kernel-8020 inputted
> get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x973ee1
> get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x1076c64
> get_amfi_out_of_my_way_patch: Patching AMFI at 0x10722a8
> main: Writing out patched file to work/kcache.patched...
> main: Quitting...
> krnl
> dtre
> rtsc
> rdsk
> hdiutil: attach failed - Permission denied
> [-] An error occurred ``` `````` `````` ```
> 
> [dualr1n hdiutil.txt](https://github.com/user-attachments/files/17669306/dualr1n.hdiutil.txt)
> ```

reboot your pc and try again

**Comment by eurosatofficial** [comment]
still occurs after reboot. I also tried on another mac and the same error occurs.

**Comment by eurosatofficial** [comment]
after a few reboots it worked but it ran straight into another error:

rdsk
/dev/disk4          	                               	/private/tmp/SSHRD
cp: /tmp/SSHRD/etc: Not a directory
other/trollstore/ -> /tmp/SSHRD
other/trollstore//usr -> /tmp/SSHRD/usr
other/trollstore//usr/trollstore -> /tmp/SSHRD/usr/trollstore
other/trollstore//usr/trollstore/PersistenceHelper -> /tmp/SSHRD/usr/trollstore/PersistenceHelper
other/trollstore//usr/trollstore/trollstorehelper -> /tmp/SSHRD/usr/trollstore/trollstorehelper
other/trollstore//usr/bin -> /tmp/SSHRD/usr/bin
other/trollstore//usr/bin/plutil -> /tmp/SSHRD/usr/bin/plutil
other/trollstore//usr/bin/trollstoreinstaller -> /tmp/SSHRD/usr/bin/trollstoreinstaller
other/trollstore//usr/bin/rsync -> /tmp/SSHRD/usr/bin/rsync
other/trollstore//usr/bin/MGGetValues -> /tmp/SSHRD/usr/bin/MGGetValues
[-] An error occurred
