### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by samh06** [edwin170/dualboot-ios-15-with-14-script#2]
I'm sure the palera1n gui for macOS can be adapted to fit this once its released?

**Comment by edwin170** [comment]
yes, I will try

**Comment by samh06** [comment]
> yes, I will try

I’m okay at swift and swiftui so I’m fine for me to do it?

**Comment by edwin170** [comment]
> > yes, I will try
> 
> I’m okay at swift and swiftui so I’m fine for me to do it?

free ?
if it is free, yes you can do it and thank you sir

**Comment by edwin170** [comment]
> > yes, I will try
> 
> I’m okay at swift and swiftui so I’m fine for me to do it?

also you can create forked https://github.com/MatthewPierson/Ramiel.git
