### ISSUE TITLE
--bypass doesn't work on iPhone6S. stuck on Apple Logo

### ISSUE THREAD

**Issue by user114030** [edwin170/dualboot-ios-15-with-14-script#3]
After running ./dualboot.sh --dualboot 14.3 and correctly dual booting, when I try to run --bypass and it finishes successfully, when I do ./dualboot.sh --boot it just gets stuck in the Apple Logo.

Any help would be greatly appreciated, thanks.

**Comment by edwin170** [comment]
That work before bypassed ?

**Comment by user114030** [comment]
Yes it did

**Comment by edwin170** [comment]
> After running ./dualboot.sh --dualboot 14.3 and correctly dual booting, when I try to run --bypass and it finishes successfully, when I do ./dualboot.sh --boot it just gets stuck in the Apple Logo.
> 
> 
> 
> Any help would be greatly appreciated, thanks.

But that boot before bypassed ?

**Comment by user114030** [comment]
(Info: My iPhone6S is iCloud Locked to Owner on iOS 15.4)

Let me list the steps I took:
1.- ./dualboot.sh --dualboot 14.3
(the script take some time and it ends up booting into the iOS 14.3 Hello screen fine)
2.- Reboot to DFU and then ./dualboot.sh --bypass 14.3
(the script runs, I see it copies some files in the logs and it ends up saying I can just reboot)
3.- It reboots to iOS 15.4, so I reboot it to DFU and run ./dualboot.sh --boot
(it boots and passes verbose boot but it gets stuck in Apple logo)

I think it may have to do with mobileactivationd not being signed or something along the lines

**Comment by edwin170** [comment]
> (Info: My iPhone6S is iCloud Locked to Owner on iOS 15.4)
> 
> 
> 
> Let me list the steps I took:
> 
> 1.- ./dualboot.sh --dualboot 14.3
> 
> (the script take some time and it ends up booting into the iOS 14.3 Hello screen fine)
> 
> 2.- Reboot to DFU and then ./dualboot.sh --bypass 14.3
> 
> (the script runs, I see it copies some files in the logs and it ends up saying I can just reboot)
> 
> 3.- It reboots to iOS 15.4, so I reboot it to DFU and run ./dualboot.sh --boot
> 
> (it boots and passes verbose boot but it gets stuck in Apple logo)
> 
> 
> 
> I think it may have to do with mobileactivationd not being signed or something along the lines

Sir yes maybe is a problem with mobile activation so I will check by please give me 40 minutes because am doing something and thanks for report

**Comment by edwin170** [comment]
If you want boot the iPhone with sshrd and sign the mobileactivationd or wait for me

**Comment by user114030** [comment]
Sure! Take all the time you need, it's fine, thanks for doing this work

Por cierto, hablo español también por si te resulta fácil hablar en español

**Comment by user114030** [comment]
> If you want boot the iPhone with sshrd and sign the mobileactivationd or wait for me
with ldid?

**Comment by user114030** [comment]
Holy shit it actually worked

In case somebody has the same issue, here are the steps:
boot into SSHRD
mount /dev/disk0s1s8 to /mnt8
cd to /mnt8/usr/libexec
ldid -e mobileactivationdBackup > mob.plist
ldid -Smob.plist mobileactivationd
/sbin/reboot

**Comment by edwin170** [comment]
> Holy shit it actually worked
> 
> 
> 
> In case somebody has the same issue, here are the steps:
> 
> boot into SSHRD
> 
> mount /dev/disk0s1s8 to /mnt8
> 
> cd to /mnt8/usr/libexec
> 
> ldid -e mobileactivationdBackup > mob.plist
> 
> ldid -Smob.plist mobileactivationd
> 
> /sbin/reboot

Gracias bro ahora se cómo arreglarlo muchas gracias y funciona bien ?

**Comment by user114030** [comment]
Puedo bootear en iOS 14.3 y puedo pasar de la pantalla Hello así que de momento todo bien, muchas gracias por el script!

**Comment by edwin170** [comment]
excellent me dices si tienes otro problema, ademas eres el primer español que yo veo usando mi script xd

**Comment by edwin170** [comment]
gracias si quieres tambien puedes hacer jailbreak

**Comment by user114030** [comment]
Estoy intentando hacer jb a ver si funciona, me estaba dando problemas con 'umount' pero he hecho 'git pull' para ver si se soluciona

**Comment by user114030** [comment]
Parece que ahora en vez de con 'umount' crasha con 'panic: Missing patch: apfs_vfsop_mount'

**Comment by edwin170** [comment]
pero que en especifico ?

> Parece que ahora en vez de con 'umount' crasha con 'panic: Missing patch: apfs_vfsop_mount'

que linea oh exactamente que ?

**Comment by edwin170** [comment]
eso pasa cuando booteas ?

> Parece que ahora en vez de con 'umount' crasha con 'panic: Missing patch: apfs_vfsop_mount'

**Comment by user114030** [comment]
Es pasa cuando hago --jailbreak 14.3
Parece que es causado por la linea "remote_cmd "/mnt8/private/var/root/Kernel15Patcher.ios /mnt4/$active/System/Library/Caches/com.apple.kernelcaches/kcache.raw /mnt4/$active/System/Library/Caches/com.apple.kernelcaches/kcache.patched""

**Comment by edwin170** [comment]
el script se detiene o continua ?

**Comment by edwin170** [comment]
> Es pasa cuando hago --jailbreak 14.3 Parece que es causado por la linea "remote_cmd "/mnt8/private/var/root/Kernel15Patcher.ios /mnt4/$active/System/Library/Caches/com.apple.kernelcaches/kcache.raw /mnt4/$active/System/Library/Caches/com.apple.kernelcaches/kcache.patched""

cuando pasa eso el script se detiene ?

**Comment by user114030** [comment]
No, la linea esa es de dentro del script, me parece que es la que causa lo de 'panic: Missing patch: apfs_vfsop_mount'

**Comment by edwin170** [comment]
> Parece que ahora en vez de con 'umount' crasha con 'panic: Missing patch: apfs_vfsop_mount'
intenta de nuevo bootear

**Comment by edwin170** [comment]
> > Parece que ahora en vez de con 'umount' crasha con 'panic: Missing patch: apfs_vfsop_mount'
> > intenta de nuevo bootear

intenta bootear de nuevo

**Comment by edwin170** [comment]
> No, la linea esa es de dentro del script, me parece que es la que causa lo de 'panic: Missing patch: apfs_vfsop_mount'

yo lo intente ahora mismo con mi iphone 6s y el problema es que tu estas intentando jailbreak 2 veces y es solo a la primera. si quieres ejecuta ./dualboot.sh --dualboot.sh --dualboot 14.3 --dont_createPart esto lo que va hacer es volver todos los archivos a la normalidad cuando eso finalize ejecuta --jailbreak. solo en caso de que da error mount_filesystem cambia 14.3 con 15.4

**Comment by edwin170** [comment]
yes sir i try it again but the normal file and that work so that is how you solve the problem. thank you for try it

**Comment by edwin170** [comment]
@user114030

**Comment by user114030** [comment]
Hey, he estado investigando porque mi 6S solo tiene 16GB y con el dualboot me quedan libres unos 300mb así que no me sirve del todo el dualboot, aunque el bypass me interesa así que estoy intentando ver si puedo de alguna forma eliminar la partición de iOS 15 sin acabar en boot loop y usar el espacio en iOS 14

**Comment by edwin170** [comment]
xd sir you know that you can delete ios 15 however that will work as if you reboot your device, you will have to use the mac to boot it

**Comment by edwin170** [comment]
> Hey, he estado investigando porque mi 6S solo tiene 16GB y con el dualboot me quedan libres unos 300mb así que no me sirve del todo el dualboot, aunque el bypass me interesa así que estoy intentando ver si puedo de alguna forma eliminar la partición de iOS 15 sin acabar en boot loop y usar el espacio en iOS 14

so be carefully and remember that if you delete ios 15 that dualboot would not be semitethered that will become a downgrade so if you want to delete ios 15 try to do apfs_deletefs /dev/disk0s1s1 and s2
