### ISSUE TITLE
No rsync

### ISSUE THREAD

**Issue by lennon1997** [edwin170/dualboot-ios-15-with-14-script#4]
Hello, I keep getting this error when I run the program any idea what's happening? 

 > krnl
> dtre
> rtsc
> rdsk
> /dev/disk3          	                               	/private/tmp/SSHRD
> cp: other/rsync/rsync: No such file or directory
> [-] An error occurred

**Comment by edwin170** [comment]
> Hello, I keep getting this error when I run the program any idea what's happening? 
> 
> 
> 
>  > krnl
> 
> > dtre
> 
> > rtsc
> 
> > rdsk
> 
> > /dev/disk3          	                               	/private/tmp/SSHRD
> 
> > cp: other/rsync/rsync: No such file or directory
> 
> > [-] An error occurred
> 
> 

Sir please give me 1 minute

**Comment by edwin170** [comment]
> Hello, I keep getting this error when I run the program any idea what's happening? 
> 
> 
> 
>  > krnl
> 
> > dtre
> 
> > rtsc
> 
> > rdsk
> 
> > /dev/disk3          	                               	/private/tmp/SSHRD
> 
> > cp: other/rsync/rsync: No such file or directory
> 
> > [-] An error occurred
> 
> 

Sir thank you for report this issues

**Comment by edwin170** [comment]
I fixed it Delete ramdisk and execute again dualboot script

**Comment by lennon1997** [comment]
Of course glad I could help out! Thank you so much I will try right now 👍

**Comment by edwin170** [comment]
great

**Comment by lennon1997** [comment]
I think it’s working the issue I was having is resolved, it’s now at a point where it keeps requesting connection to USB device handle 3.

**Comment by edwin170** [comment]
sorry sir. fuck ramdisk 
wait please

**Comment by edwin170** [comment]
sorry sir. fuck ramdisk 
wait please

**Comment by lennon1997** [comment]
No problem!

**Comment by edwin170** [comment]
delete ramdisk
and execute again 
sorry for the problems sir

**Comment by edwin170** [comment]
> delete ramdisk and execute again sorry for the problems sir

remeber git pull

**Comment by edwin170** [comment]
are you trying on linux or macos ? because that work only on macos for now

**Comment by lennon1997** [comment]
Macos I think its working now I've seen this before when it did work for me.

> Compiled with plist: YES
> Saved IM4M to work/IM4M
> [*] Creating partitions
> is already created
> [*] partitions created, continuing...
> mounting filesystems 
> ./dualboot.sh: line 736: [: too many arguments
> copying filesystem so hang on that could take 20 minute because is trought ssh
> rsync installed
> sh: rsync: command not found
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: remote command not found (code 127) at io.c(231) [sender=3.2.7]
>

**Comment by edwin170** [comment]
git pull sir and delete ramdisk

**Comment by edwin170** [comment]
you dont have updated

**Comment by lennon1997** [comment]
I did that but I will try again.

**Comment by edwin170** [comment]
so if the script does not stop, be patient please

**Comment by lennon1997** [comment]
Okay sounds good I will let it run, thank you!

**Comment by edwin170** [comment]
> Okay sounds good I will let it run, thank you!
np

**Comment by lennon1997** [comment]
it rebooted into recovery and asked me to put it into dfu mode again but I messed up and it went to the apple logo so I'm trying it again

**Comment by edwin170** [comment]
> it rebooted into recovery and asked me to put it into dfu mode again but I messed up and it went to the apple logo so I'm trying it again

try with this command in order to dont have to recopy again

**Comment by edwin170** [comment]
because you have already create the partition

**Comment by lennon1997** [comment]
Oh shoot I already started again should I leave it or cancel and try with that command?

**Comment by edwin170** [comment]
let it continue

**Comment by edwin170** [comment]
> Oh shoot I already started again should I leave it or cancel and try with that command?

let it continue

**Comment by lennon1997** [comment]
it ran and then exited here the phone just has the ramdisk picture on it not sure if anything is still happening

**Comment by edwin170** [comment]
> it ran and then exited here the phone just has the ramdisk picture on it not sure if anything is still happening

Yes is normal that take like 15 minutes

**Comment by edwin170** [comment]
> it ran and then exited here the phone just has the ramdisk picture on it not sure if anything is still happening

The script stop ?

**Comment by edwin170** [comment]
> > it ran and then exited here the phone just has the ramdisk picture on it not sure if anything is still happening
> 
> The script stop ? If not could you send me a photo please

**Comment by lennon1997** [comment]
![image](https://user-images.githubusercontent.com/12139923/206815031-b2b8b21e-b730-4777-b29f-c5257749a7bd.jpg)

**Comment by edwin170** [comment]
That is weird

**Comment by lennon1997** [comment]
okay I'll try that if not I'll do a restore and try again this is an older device anyways so not a big deal to restore it

**Comment by edwin170** [comment]
> okay I'll try that if not I'll do a restore and try again this is an older device anyways so not a big deal to restore it

Sir did you do --dualboot 14.3 --dont_createPart

**Comment by edwin170** [comment]
?

**Comment by lennon1997** [comment]
just trying now

**Comment by edwin170** [comment]
Also you don't have to restore you can use --restorerootfs which delete the dualboot

**Comment by lennon1997** [comment]
did this and quit 

> extracting ipsw, hang on please ...
> Archive:  ipsw/iPhone_4.7_14.3_18C66_Restore.ipsw
> ipsw/extracted//BuildManifest.plist -> work/BuildManifest.plist
> asr -source ipsw/extracted/038-82971-079.dmg -target ipsw/out.dmg --embed -erase -noprompt --chunkchecksum --puppetstrings

**Comment by edwin170** [comment]
> just trying now

Ok sir

**Comment by edwin170** [comment]
rm blobs/*

**Comment by lennon1997** [comment]
iPhone8,1-14.3.shsh2   iPhone8,1-15.7.1.shsh2

thats what it shows. I should run that rm blobs/* command next?

**Comment by edwin170** [comment]
Yes

**Comment by edwin170** [comment]
> > okay I'll try that if not I'll do a restore and try again this is an older device anyways so not a big deal to restore it
> 
> Sir did you do --dualboot 14.3 --dont_createPart 

So after that execute this again

**Comment by lennon1997** [comment]
okay doing now

**Comment by lennon1997** [comment]
worked, thank you!

**Comment by edwin170** [comment]
hello screen sir 

> worked, thank you!

hello screen sir ?

**Comment by edwin170** [comment]
> worked, thank you!

np sir thank you for try it

**Comment by lennon1997** [comment]
![image](https://user-images.githubusercontent.com/12139923/206819053-48455a37-6033-428f-8d49-a86c053ab21b.png)

**Comment by edwin170** [comment]
> ![image](https://user-images.githubusercontent.com/12139923/206819053-48455a37-6033-428f-8d49-a86c053ab21b.png)

boot ?

**Comment by edwin170** [comment]
> it booted ya, if you mean the bootup on the phone it happened too fast for me to get a video of it sorry

np

**Comment by edwin170** [comment]
> it booted ya, if you mean the bootup on the phone it happened too fast for me to get a video of it sorry

work fine sir ?

**Comment by lennon1997** [comment]
Yes it worked just trying to see if I can get the jailbreak to work but I’m taking a break for the night Sent from my iPhoneOn Dec 9, 2022, at 8:26 PM, edwin ***@***.***> wrote:﻿

it booted ya, if you mean the bootup on the phone it happened too fast for me to get a video of it sorry

work fine sir ?

**Comment by edwin170** [comment]
> Yes it worked just trying to see if I can get the jailbreak to work but I’m taking a break for the night Sent from my iPhoneOn Dec 9, 2022, at 8:26 PM, edwin ***@***.***> wrote:﻿
> 
> it booted ya, if you mean the bootup on the phone it happened too fast for me to get a video of it sorry
> 
> work fine sir ?
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Ok sir nice, if you want you can use pogo or taurine I recommend pogo

**Comment by lennon1997** [comment]
Okay I will try tomorrow and post how it goes thank you Sent from my iPhoneOn Dec 9, 2022, at 8:29 PM, edwin ***@***.***> wrote:﻿

Yes it worked just trying to see if I can get the jailbreak to work but I’m taking a break for the night Sent from my iPhoneOn Dec 9, 2022, at 8:26 PM, edwin @.***> wrote:﻿
it booted ya, if you mean the bootup on the phone it happened too fast for me to get a video of it sorry
work fine sir ?
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***>

Ok sir nice, if you want you can use pogo or taurine I recommend pogo

**Comment by edwin170** [comment]
> Okay I will try tomorrow and post how it goes thank you Sent from my iPhoneOn Dec 9, 2022, at 8:29 PM, edwin ***@***.***> wrote:﻿
> 
> Yes it worked just trying to see if I can get the jailbreak to work but I’m taking a break for the night Sent from my iPhoneOn Dec 9, 2022, at 8:26 PM, edwin @.***> wrote:﻿
> it booted ya, if you mean the bootup on the phone it happened too fast for me to get a video of it sorry
> work fine sir ?
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***>
> 
> Ok sir nice, if you want you can use pogo or taurine I recommend pogo
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Nice sir and thank you

**Comment by edwin170** [comment]
> Okay I will try tomorrow and post how it goes thank you Sent from my iPhoneOn Dec 9, 2022, at 8:29 PM, edwin ***@***.***> wrote:﻿ Yes it worked just trying to see if I can get the jailbreak to work but I’m taking a break for the night Sent from my iPhoneOn Dec 9, 2022, at 8:26 PM, edwin @.***> wrote:﻿ it booted ya, if you mean the bootup on the phone it happened too fast for me to get a video of it sorry work fine sir ? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***> Ok sir nice, if you want you can use pogo or taurine I recommend pogo —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

ah sir remember that before you --jailbreak it you have to delete ramdisk and git pull because i fixed it some problems
