### ISSUE TITLE
Jailbreak 

### ISSUE THREAD

**Issue by lennon1997** [edwin170/dualboot-ios-15-with-14-script#5]
Hello, trying to jailbreak the second iOS now but the instructions are a bit unclear to me. I've downloaded the SSHRD_Script repository and ran ./sshrd.sh 14.3 Trollstore Tips and now when I open the tips app it just crashes. Some clarification would be much appreciated!

**Comment by edwin170** [comment]
open tv

**Comment by edwin170** [comment]
> Hello, trying to jailbreak the second iOS now but the instructions are a bit unclear to me. I've downloaded the SSHRD_Script repository and ran ./sshrd.sh 14.3 Trollstore Tips and now when I open the tips app it just crashes. Some clarification would be much appreciated!

open tv app please

**Comment by edwin170** [comment]
and install trollstore there

**Comment by lennon1997** [comment]
Okay got it thank you!

**Comment by edwin170** [comment]
> Okay got it thank you!

nice i recommend you install pogo
