### ISSUE TITLE
Apple ID

### ISSUE THREAD

**Issue by lennon1997** [edwin170/dualboot-ios-15-with-14-script#8]
Can I sign into appleid on 14.3 boot without bypass or is bypass always needed for that? I tried without because I know the login info but it says software update required.

**Comment by edwin170** [comment]
> Can I sign into appleid on 14.3 boot without bypass or is bypass always needed for that? I tried without because I know the login info but it says software update required.

Is not needed, you can login iCloud normal, I put bypass because someone could forget the password of the login

**Comment by edwin170** [comment]
> Can I sign into appleid on 14.3 boot without bypass or is bypass always needed for that? I tried without because I know the login info but it says software update required.

I login to my account in iOS 14.3 and that does not say anything

**Comment by edwin170** [comment]
> Can I sign into appleid on 14.3 boot without bypass or is bypass always needed for that? I tried without because I know the login info but it says software update required.

Can you take a photo and send me ?

**Comment by lennon1997** [comment]
Okay I uninstalled the second iOS to try and fix it so once I have it back if the issue is still occuring I will post back with a photo of the error.

**Comment by edwin170** [comment]
> Okay I uninstalled the second iOS to try and fix it so once I have it back if the issue is still occuring I will post back with a photo of the error.

Ok bro, but  is that working fine?

**Comment by edwin170** [comment]
> > Okay I uninstalled the second iOS to try and fix it so once I have it back if the issue is still occuring I will post back with a photo of the error.
> 
> Ok bro, but  is that working fine? 

Or did you fix th error of software need update?

**Comment by lennon1997** [comment]
I don't have the ios 14.3 on my phone currently I'm gonna reinstall it sometime today. I think the issue may be because it asked me to sign in on ios 15.7.1 but I did not do that and tried only on 14.3. I'll let you know if its working on my next try. Thank you

**Comment by edwin170** [comment]
> I don't have the ios 14.3 on my phone currently I'm gonna reinstall it sometime today. I think the issue may be because it asked me to sign in on ios 15.7.1 but I did not do that and tried only on 14.3. I'll let you know if its working on my next try. Thank you

Nice bro
